---
framework: jasmine
preRun:
     command:
        - npm install
postMerge:
  pattern:
    - "spec/**/*[sS]pec.{js,mjs}"
preMerge:
  pattern:
    - "spec/**/*[sS]pec.{js,mjs}"
configFile: "spec/support/jasmine.json"
version: 1.0.0

